### ISSUE TITLE
Fails to install via NPM on Raspberry Pi

### ISSUE THREAD

**Issue by dermotos** [sandeepmistry/noble#126]
Attempting to install via `npm install noble` (both as regular and sudo)

Receive the following error:

npm install noble
|
> noble@0.3.7 install /home/pi/app/node_modules/noble
> node install.js

noble install: platform is "linux'
noble install: running node-gyp ...
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.35"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/app/node_modules/noble/.node-gyp"
make: Entering directory `/home/pi/app/node_modules/noble/build'
  CC(target) Release/obj.target/hci-ble/src/hci-ble.o
../src/hci-ble.c:9:33: fatal error: bluetooth/bluetooth.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/hci-ble/src/hci-ble.o] Error 1
make: Leaving directory `/home/pi/app/node_modules/noble/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.6.11+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/pi/app/node_modules/noble
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
noble install: done

npm ERR! noble@0.3.7 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the noble@0.3.7 install script.
npm ERR! This is most likely a problem with the noble package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls noble
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.6.11+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "noble"
npm ERR! cwd /home/pi/app
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by dermotos** [comment]
My mistake, missed your extra steps...
`sudo apt-get install bluetooth bluez-utils libbluetooth-dev`
