### ISSUE TITLE
TypeError: Cannot read property 'uuid' of undefined

### ISSUE THREAD

**Issue by ManuelOverdijk** [sandeepmistry/noble#166]
Hey guys,

I get the following error: 
```javascript
/node_modules/noble/lib/mac/yosemite.js:411
serviceUuid = this._peripherals[deviceUuid].services[serviceStartHandle].uuid;
                                                                      ^
TypeError: Cannot read property 'uuid' of undefined

```

while trying to read a characteristic using the following code from the Getting Started tutorial

```javascript
this._peripheral.discoverServices(['180f'], function(error, services) {
				var deviceInformationService = services[0];
				deviceInformationService.discoverCharacteristics([], function(error, characteristics) {
					var manufacturerNameCharacteristic = characteristics[0];
					manufacturerNameCharacteristic.read(function(error, data) {
						// data is a buffer
						console.log('manufacture name is: ' + data.toString('utf8'));
					});
				});
			});

```
I'm currently using Noble 0.3.12 and the peripheral is connected, and has a service with UUID 180f. Is this  an issue on my part, or is something else going on here?

**Comment by sandeepmistry** [comment]
@ManuelOverdijk could you please provide debug output:

```sh
DEBUG=* node <file>.js
```

Also, would you be able to share more of your code?

**Comment by matthewnourse** [comment]
@sandeepmistry I'm getting a similar error but in a uuid-to-address.js.  I've added this line to uuid-to-address.js in my local copy to help with debugging:

```
console.log("obj=", require('util').inspect(obj, {showHidden: true, depth: null}));
```

My code:

```
var noble = require('noble');

noble.startScanning();

noble.on('discover', function(peripheral) {
  console.log("peripheral=", peripheral);
});
```

I ran it with this command line on Mac OS (Yosemite):
```
env NODE_PATH=.:/usr/local/lib/node_modules DEBUG=* node cadenceAlarm.js > debug.out 2>&1
```

The contents of debug.out:

```
Fri, 17 Apr 2015 11:09:20 GMT yosemite-bindings sendCBMsg: 1, {
  "kCBMsgArgName": "node-1429268960474",
  "kCBMsgArgOptions": {
    "kCBInitOptionShowPowerAlert": 0
  },
  "kCBMsgArgType": 0
}
Fri, 17 Apr 2015 11:09:20 GMT yosemite-bindings sendCBMsg: 29, {
  "kCBMsgArgOptions": {},
  "kCBMsgArgUUIDs": []
}
Fri, 17 Apr 2015 11:09:20 GMT noble scanStart
Fri, 17 Apr 2015 11:09:20 GMT yosemite-bindings xpcEvent: {
  "kCBMsgId": 6,
  "kCBMsgArgs": {
    "kCBMsgArgState": 5
  }
}
Fri, 17 Apr 2015 11:09:20 GMT yosemite-bindings state change poweredOn
Fri, 17 Apr 2015 11:09:20 GMT noble stateChange poweredOn
Fri, 17 Apr 2015 11:09:29 GMT yosemite-bindings xpcEvent: {
  "kCBMsgId": 37,
  "kCBMsgArgs": {
    "kCBMsgArgAdvertisementData": {
      "kCBAdvDataIsConnectable": 1,
      "kCBAdvDataServiceUUIDs": [
        {
          "type": "Buffer",
          "data": [
            24,
            22
          ]
        }
      ],
      "kCBAdvDataLocalName": "RPM"
    },
    "kCBMsgArgRssi": -59,
    "kCBMsgArgDeviceUUID": {
      "type": "Buffer",
      "data": [
        0,
        230,
        10,
        139,
        105,
        81,
        66,
        164,
        177,
        153,
        178,
        248,
        228,
        129,
        139,
        255
      ]
    },
    "kCBMsgArgName": "RPM"
  }
}
Fri, 17 Apr 2015 11:09:29 GMT yosemite-bindings peripheral 00e60a8b695142a4b199b2f8e4818bff discovered
Fri, 17 Apr 2015 11:09:29 GMT yosemite-bindings xpcEvent: {
  "kCBMsgId": 37,
  "kCBMsgArgs": {
    "kCBMsgArgAdvertisementData": {
      "kCBAdvDataIsConnectable": 1
    },
    "kCBMsgArgRssi": -59,
    "kCBMsgArgDeviceUUID": {
      "type": "Buffer",
      "data": [
        0,
        230,
        10,
        139,
        105,
        81,
        66,
        164,
        177,
        153,
        178,
        248,
        228,
        129,
        139,
        255
      ]
    },
    "kCBMsgArgName": "RPM"
  }
}
Fri, 17 Apr 2015 11:09:29 GMT yosemite-bindings peripheral 00e60a8b695142a4b199b2f8e4818bff discovered
obj= [ { PairedDevices: [ 'cc-9e-00-ec-58-39', [length]: 1 ],
    IgnoredDevices: [ [length]: 0 ],
    BRPairedDevices: [ 'cc-9e-00-ec-58-39', [length]: 1 ],
    ControllerPowerState: 1,
    PANInterfaces: [ '80-49-71-13-43-98', [length]: 1 ],
    HIDDevices: [ 'cc-9e-00-ec-58-39', [length]: 1 ],
    DeviceCache: 
     { 'c0-df-be-f5-26-8e': 
        { LastNameUpdate: Fri Apr 17 2015 20:39:37 GMT+1000 (AEST),
          Appearance: 1157,
          Name: 'RPM' },
       'cc-9e-00-ec-58-39': 
        { LastServicesUpdate: Sun Mar 08 2015 16:04:50 GMT+1100 (AEDT),
          Name: 'Nintendo RVL-CNT-01',
          LMPSubversion: 796,
          InquiryRSSI: 208,
          SupportedFeatures: <Buffer 00 00 00 08 38 04 02 bc>,
          LastNameUpdate: Sat Feb 21 2015 18:45:28 GMT+1100 (AEDT),
          PageScanPeriod: 0,
          LMPVersion: 3,
          PageScanRepetitionMode: 1,
          LastInquiryUpdate: Sun Mar 08 2015 16:04:43 GMT+1100 (AEDT),
          Services: <Buffer 04 0b 73 74 72 65 61 6d 74 79 70 65 64 81 e8 03 84 01 40 84 84 84 07 4e 53 41 72 72 61 79 00 84 84 08 4e 53 4f 62 6a 65 63 74 00 85 84 01 69 03 92 84 ... >,
          PageScanMode: 0,
          ClassOfDevice: 9476,
          ClockOffset: 6740,
          Manufacturer: 15 },
       '00-26-b0-fb-26-ee': 
        { ClassOfDevice: 3801348,
          PageScanRepetitionMode: 1,
          ClockOffset: 18991,
          PageScanMode: 0,
          EIRData: <Buffer 05 09 6d 69 6e 69 0f 03 0a 11 0c 11 1f 11 01 11 00 10 12 11 17 11 0e ff 4c 00 01 4d 61 63 6d 69 6e 69 33 2c 31 00 00 00 00 00 00 00 00 00 00 00 00 00 ... >,
          LastNameUpdate: Sat Aug 25 2012 21:14:27 GMT+1000 (AEST),
          Name: 'mini',
          ModelIdentifier: 'Macmini3,1\u0000',
          PageScanPeriod: 0,
          LastInquiryUpdate: Sat Aug 25 2012 21:14:27 GMT+1000 (AEST) },
       '74-f0-6d-d9-64-6c': 
        { PageScanRepetitionMode: 1,
          ClockOffset: 14055,
          PageScanMode: 0,
          EIRData: <Buffer 0a 09 4c 49 5a 41 52 44 2d 50 43 02 0a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... >,
          LastNameUpdate: Thu Apr 24 2014 08:01:01 GMT+1000 (AEST),
          InquiryRSSI: 182,
          Name: 'LIZARD-PC',
          PageScanPeriod: 0,
          ClassOfDevice: 4063500,
          LastInquiryUpdate: Thu Apr 24 2014 08:01:01 GMT+1000 (AEST) },
       'd8-6b-f7-3d-60-6b': 
        { Name: 'Nintendo RVL-CNT-01',
          LMPSubversion: 796,
          InquiryRSSI: 206,
          LastNameUpdate: Sat Feb 21 2015 17:01:55 GMT+1100 (AEDT),
          PageScanPeriod: 0,
          SupportedFeatures: <Buffer 00 00 00 08 38 04 02 bc>,
          LMPVersion: 3,
          PageScanRepetitionMode: 1,
          LastInquiryUpdate: Sat Feb 21 2015 17:01:55 GMT+1100 (AEDT),
          Manufacturer: 15,
          ClockOffset: 5657,
          PageScanMode: 0,
          ClassOfDevice: 9476 } },
    PersistentPorts: 
     { 'incoming port - Bluetooth-Incoming-Port': 
        { BTName: 'incoming port - Bluetooth-Incoming-Port',
          P49SerialPort: 1,
          HiddenPort: 1,
          IOTTYBaseName: 'Bluetooth-Incoming-Port',
          BTRFCOMMChannel: 3,
          BTAuthenticationRequired: false,
          BTSerialConnectionType: 0,
          BTPSM: 3,
          BTEncryptionType: false,
          BTTTYName: 'Bluetooth-Incoming-Port' },
       'Bluetooth-Modem': 
        { BTName: 'Bluetooth-Modem',
          P49SerialPort: 1,
          BTPSM: 0,
          BTRFCOMMChannel: 0,
          IOTTYBaseName: 'Bluetooth-Modem',
          BTAuthenticationRequired: 0,
          BTAddress: <Buffer >,
          BTTTYName: 'Bluetooth-Modem' } },
    'D2D MAC Address': <Buffer 02 00 ea f5 4e 60>,
    PersistentPortsServices: 
     { 'incoming port - Bluetooth-PDA-Sync': 
        { '0005 - BrowseGroupList*': [ <Buffer 10 02>, [length]: 1 ],
          '0004 - ProtocolDescriptorList': 
           [ [ <Buffer 01 00>, [length]: 1 ],
             [ <Buffer 00 03>,
               { DataElementType: 1, DataElementValue: 3, DataElementSize: 1 },
               [length]: 2 ],
             [length]: 2 ],
          '0100 - ServiceName*': 'Bluetooth-PDA-Sync',
          '0006 - LanguageBaseAttributeIDList*': 
           [ { DataElementType: 1,
               DataElementValue: 25966,
               DataElementSize: 2 },
             { DataElementType: 1, DataElementValue: 106, DataElementSize: 2 },
             { DataElementType: 1, DataElementValue: 256, DataElementSize: 2 },
             [length]: 3 ],
          '0000 - ServiceRecordHandle*': 65540,
          '0001 - ServiceClassIDList': [ <Buffer 11 01>, [length]: 1 ],
          '0009 - BluetoothProfileDescriptorList': 
           [ [ <Buffer 11 01>,
               { DataElementType: 1, DataElementValue: 256, DataElementSize: 2 },
               [length]: 2 ],
             [length]: 1 ] },
       'incoming port - Bluetooth-Incoming-Port': 
        { '0005 - BrowseGroupList*': [ <Buffer 10 02>, [length]: 1 ],
          '0004 - ProtocolDescriptorList': 
           [ [ <Buffer 01 00>, [length]: 1 ],
             [ <Buffer 00 03>,
               { DataElementType: 1, DataElementValue: 3, DataElementSize: 1 },
               [length]: 2 ],
             [length]: 2 ],
          '0100 - ServiceName*': 'Bluetooth-Incoming-Port',
          '0006 - LanguageBaseAttributeIDList*': 
           [ { DataElementType: 1,
               DataElementValue: 25966,
               DataElementSize: 2 },
             { DataElementType: 1, DataElementValue: 106, DataElementSize: 2 },
             { DataElementType: 1, DataElementValue: 256, DataElementSize: 2 },
             [length]: 3 ],
          '0000 - ServiceRecordHandle*': 65540,
          '0001 - ServiceClassIDList': [ <Buffer 11 01>, [length]: 1 ],
          '0009 - BluetoothProfileDescriptorList': 
           [ [ <Buffer 11 01>,
               { DataElementType: 1, DataElementValue: 256, DataElementSize: 2 },
               [length]: 2 ],
             [length]: 1 ] } },
    BluetoothVersionNumber: 3 },
  [length]: 1 ]
/usr/local/lib/node_modules/noble/lib/mac/uuid-to-address.js:19
    var coreBluetoothCacheEntry = obj[0].CoreBluetoothCache[formattedUuid];
                                                           ^
TypeError: Cannot read property '00E60A8B-6951-42A4-B199-B2F8E4818BFF' of undefined
    at /usr/local/lib/node_modules/noble/lib/mac/uuid-to-address.js:19:60
    at tryParseBuffer (/usr/local/lib/node_modules/noble/node_modules/bplist-parser/bplistParser.js:25:5)
    at /usr/local/lib/node_modules/noble/node_modules/bplist-parser/bplistParser.js:33:7
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
```

Thanks for noble, it looks very cool.

**Comment by sandeepmistry** [comment]
@matthewnourse it's a separate issue: https://github.com/sandeepmistry/noble/issues/168 - should be addressed in the v0.3.14 release ...

**Comment by sandeepmistry** [comment]
@ManuelOverdijk any updates (debug logs, code) on this?

**Comment by matthewnourse** [comment]
@sandeepmistry perfect, I upgraded to v0.3.14 and it works great now, thanks, and sorry that I missed #168.

**Comment by sandeepmistry** [comment]
Closing due to lack of activity ...
