### ISSUE TITLE
readDeviceName from sensortag library complains about noble

### ISSUE THREAD

**Issue by vertexclique** [sandeepmistry/noble#250]
Error: characteristic uuid 2a00 not found in service uuid 1800!
    at NobleDevice.readDataCharacteristic (/home/vertexclique/projects/blabla/node_modules/sensortag/node_modules/noble-device/lib/noble-device.js:85:21)
    at NobleDevice.readStringCharacteristic (/home/vertexclique/projects/blabla/node_modules/sensortag/node_modules/noble-device/lib/noble-device.js:133:8)
    at NobleDevice.readDeviceName (/home/vertexclique/projects/blabla/node_modules/sensortag/node_modules/noble-device/lib/noble-device.js:222:8)
    at /home/vertexclique/projects/blabla/src/sensortag.js:25:17
    at readDeviceName (/home/vertexclique/projects/blabla/src/sensortag.js:23:10)
    at /home/vertexclique/projects/blabla/src/sensortag.js:16:17
    at null.<anonymous> (/home/vertexclique/projects/blabla/node_modules/sensortag/node_modules/noble-device/lib/noble-device.js:76:7)
    at null.<anonymous> (/home/vertexclique/projects/blabla/node_modules/sensortag/node_modules/noble-device/lib/noble-device.js:64:5)
    at Peripheral.<anonymous> (/home/vertexclique/projects/blabla/node_modules/sensortag/node_modules/noble-device/node_modules/noble/lib/peripheral.js:101:13)
    at Service.<anonymous> (/home/vertexclique/projects/blabla/node_modules/sensortag/node_modules/noble-device/node_modules/noble/lib/service.js:53:7)
From previous event:
    at EventEmitter.onDiscover (/home/vertexclique/projects/blabla/src/sensortag.js:173:5)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at Noble.constructor.onDiscover (/home/vertexclique/projects/blabla/node_modules/sensortag/node_modules/noble-device/lib/util.js:30:29)
    at emitOne (events.js:82:20)
    at Noble.emit (events.js:169:7)
    at Noble.onDiscover (/home/vertexclique/projects/blabla/node_modules/sensortag/node_modules/noble-device/node_modules/noble/lib/noble.js:144:10)

**Comment by sandeepmistry** [comment]
@vertexclique OS X does not allow access to the 0x1800 service, there's nothing noble can do about this unfortunately.
