### ISSUE TITLE
Error using noble with nw.js

### ISSUE THREAD

**Issue by franciscodelicado** [sandeepmistry/noble#338]
I am trying to use noble with nw.js, but when I start scanning I obtain following error:

$nw .
[10210:0220/123202:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[10210:0220/123208:ERROR:nw_shell.cc(336)] Error: Could not start scanning, state is unknown (not poweredOn)
    at Noble.startScanning (/home/franman/node_modules/noble/lib/noble.js:88:17)
    at Object.bean_app.connect (file:///home/franman/documents/docencia/DRI/BlueTooth/practicas/Bean-app/bean_app.js:56:8)
    at HTMLInputElement.<anonymous> (file:///home/franman/documents/docencia/DRI/BlueTooth/practicas/Bean-app/bean_app.js:45:12)
    at HTMLInputElement.n.event.dispatch (file:///home/franman/documents/docencia/DRI/BlueTooth/practicas/Bean-app/libs/jquery-1.12.0.min.js:3:12344)
    at HTMLInputElement.r.handle (file:///home/franman/documents/docencia/DRI/BlueTooth/practicas/Bean-app/libs/jquery-1.12.0.min.js:3:9078)
[10210:0220/123208:INFO:CONSOLE(93)] "Uncaught Error: Could not start scanning, state is unknown (not poweredOn)", source: /home/franman/node_modules/noble/lib/noble.js (93)

It looks like the system can not access to bluetooth_hci_socket well, because the state of the bluetooth interface is **unknwon**

Before that, I rebuilt in nw.js native mode bluetooth_hci_socket module.

Any ideas?

**Comment by sandeepmistry** [comment]
@franciscodelicado it looks like you are starting scanning without waiting for a state change event.

Please see the examples for required code flow .... https://github.com/sandeepmistry/noble/blob/master/examples/advertisement-discovery.js
