### ISSUE TITLE
test.js:49: "TypeError: Cannot read property 'on' of undefined"

### ISSUE THREAD

**Issue by T-X** [sandeepmistry/noble#376]
Running "$ DEBUG=* nodejs ./test.js > /tmp/crash.log 2>&1" I currently get the following crash:

<pre>
/home/nbsp/dev/noble/test.js:49
    services[serviceIndex].on('includedServicesDiscover', function(includedServiceUuids) {
                          ^

TypeError: Cannot read property 'on' of undefined
    at Peripheral.<anonymous> (/home/nbsp/dev/noble/test.js:49:27)
    at emitOne (events.js:77:13)
    at Peripheral.emit (events.js:169:7)
    at Noble.onServicesDiscover (/home/nbsp/dev/noble/lib/noble.js:225:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at NobleBindings.onServicesDiscovered (/home/nbsp/dev/noble/lib/hci-socket/bindings.js:291:8)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at null.<anonymous> (/home/nbsp/dev/noble/lib/hci-socket/gatt.js:330:12)
</pre>

See the attached dumps (hcidump -t -x) and logs for details:

[crash.txt](https://github.com/sandeepmistry/noble/files/208621/crash.txt)
[hcidump.txt](https://github.com/sandeepmistry/noble/files/208622/hcidump.txt)

It had worked before today. Doing a "hciconfig hci0 down; hciconfig hci0 up" did not seem to help though. Unplugging and replugging does not help either.

The device is a Linux 3.16, Debian testing, x86.

Sometimes things crash ten lines later, too (ref. #360):

<pre>
  att a4:77:33:a3:b6:93: write: 100100ffff0028 +2ms
  hci write acl data pkt - writing: 0245000b0007000400100100ffff0028 +1ms
  hci onSocketData: 024520180014000400110601000500011814001c0000182800ffffa0fe +31ms
  hci   event type = 2 +0ms
  hci           cid = 4 +1ms
  hci           handle = 69 +0ms
  hci           data = 110601000500011814001c0000182800ffffa0fe +0ms
on -> peripheral services discovered {"uuid":"1801","name":"Generic Attribute","type":"org.bluetooth.service.generic_attribute","includedServiceUuids":null},{"uuid":"1800","name":"Generic Access","type":"org.bluetooth.service.generic_access","includedServiceUuids":null},{"uuid":"fea0","name":null,"type":null,"includedServiceUuids":null}
  att a4:77:33:a3:b6:93: write: 08010005000228 +6ms
  hci write acl data pkt - writing: 0245000b000700040008010005000228 +0ms
  hci onSocketData: 024520070003000400030001 +0ms
  hci   event type = 2 +0ms
  hci           cid = 4 +0ms
  hci           handle = 69 +0ms
  hci           data = 030001 +0ms
on -> service included services discovered
  att a4:77:33:a3:b6:93: write: 08010005000328 +3ms
  hci write acl data pkt - writing: 0245000b000700040008010005000328 +1ms
  hci onSocketData: 024520180014000400110601000500011814001c0000182800ffffa0fe +4ms
  hci   event type = 2 +0ms
  hci           cid = 4 +0ms
  hci           handle = 69 +1ms
  hci           data = 110601000500011814001c0000182800ffffa0fe +0ms
on -> service characteristics discovered
  hci set scan enabled - writing: 010c20020001 +4ms
  hci disconnect - writing: 01060403450013 +0ms
/home/nbsp/dev/noble/test.js:59
      characteristics[characteristicIndex].on('read', function(data, isNotification) {
                                          ^

TypeError: Cannot read property 'on' of undefined
    at Service.<anonymous> (/home/nbsp/dev/noble/test.js:59:43)
    at emitOne (events.js:77:13)
    at Service.emit (events.js:169:7)
    at Noble.onCharacteristicsDiscover (/home/nbsp/dev/noble/lib/noble.js:276:13)
    at emitThree (events.js:97:13)
    at emit (events.js:175:7)
    at NobleBindings.onCharacteristicsDiscovered (/home/nbsp/dev/noble/lib/hci-socket/bindings.js:325:8)
    at emitThree (events.js:97:13)
    at emit (events.js:175:7)
    at null.<anonymous> (/home/nbsp/dev/noble/lib/hci-socket/gatt.js:461:12)
</pre>

Another EDIT: Btw., running "$ DEBUG=* nodejs node-bleacon/estimote-sticker/test.js" works fine without any crashes.

**Comment by sandeepmistry** [comment]
Yep, test.js is just a random test app, it is not designed to work with any peripheral so crashes are expected. The files in the examples folder are more robust.
