### ISSUE TITLE
Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by gustavotemple** [sandeepmistry/noble#404]
Hello guys!

When I try to run any example (e.g. the "test.js"):
```
~/Desktop/noble-1.5.0 $ sudo node test.js 
noble
on -> stateChange: poweredOn
on -> scanStart
on -> discover: {"id":"38c986e7a721","address":"38:c9:86:e7:a7:21","addressType":"public","connectable":true,"advertisement":{"localName":"test","serviceData":[],"serviceUuids":["fffffffffffffffffffffffffffffff0"]},"rssi":-64,"state":"disconnected"}
on -> scanStop
on -> connect
on -> RSSI update -74
on -> peripheral services discovered 
/home/gustavo/Desktop/noble-1.5.0/test.js:49
    services[serviceIndex].on('includedServicesDiscover', function(includedServiceUuids) {
                          ^
TypeError: Cannot read property 'on' of undefined
    at Peripheral.<anonymous> (/home/gustavo/Desktop/noble-1.5.0/test.js:49:27)
    at emitOne (events.js:77:13)
    at Peripheral.emit (events.js:169:7)
    at Noble.onServicesDiscover (/home/gustavo/Desktop/noble-1.5.0/lib/noble.js:218:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at NobleBindings.onServicesDiscovered (/home/gustavo/Desktop/noble-1.5.0/lib/hci-socket/bindings.js:291:8)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at null.<anonymous> (/home/gustavo/Desktop/noble-1.5.0/lib/hci-socket/gatt.js:334:12)
```

Noble:
`noble-1.5.0`

Bleno:
`bleno-0.4.0`

Bleno output:
```
~/Desktop/bleno-0.4.0 $ sudo node test.js 
[sudo] password for user: 
bleno
on -> stateChange: poweredOn, address = 38:c9:86:e7:a7:21
on -> advertisingStart: success
on -> servicesSet: success
on -> accept, client: 38:c9:86:e7:9d:69
on -> rssiUpdate: -74
on -> disconnect, client: 38:c9:86:e7:9d:69
```

My Linux distribution:
```
$ uname -a
Linux 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

The bluez version:
```
$ ./bluetoothd -v
5.28
```

The nodejs version:
```
$ node -v
v4.4.4
```

The Wireshark "Sent LE Set Advertising Data" frame:
```
Data Type Value: 0x06
Data Type Name: Incomplete List of 128-bit Service Class UUIDs
```

Does anyone know what's happening?

**Comment by sandeepmistry** [comment]
noble test.js is not compatible with anything really.

I would suggest using the examples from the examples folder: https://github.com/sandeepmistry/noble/tree/master/examples
