### ISSUE TITLE
Noble not working with Electron

### ISSUE THREAD

**Issue by aditya02maurya** [sandeepmistry/noble#444]
Trying to create an **Electron** application using noble module.

With **Electron** got this error while `npm start.` 

    A JavaScript error occurred in the main process.

    [Content]
    Uncaught Exception:
    Error: A dynamic link library (DLL) initialization routine failed.
    \\?\F:\electron_boilerplate\electron-boilerplate\build\node_modules\noble\node_modules\bluetooth-hci-socket\node_modules\usb\src\binding\usb_bindings.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:167:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:167:20)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous>(F:\electron_boilerplate\electron-boilerplate\build\node_modules\noble\node_modules\bluetooth-hci-socket\node_modules\usb\usb.js:5:38)

**Comment by sandeepmistry** [comment]
@aditya02maurya please see https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md

You need to rebuild the native modules to work with electron.
