### ISSUE TITLE
Unhandled TypeError on exit on Windows 10

### ISSUE THREAD

**Issue by gfwilliams** [sandeepmistry/noble#502]
Hi! I'm getting the following error:

```
C:\workspace\EspruinoTools\node_modules\bluetooth-hci-socket\lib\usb.js:120
      this._usbDevice.controlTransfer(usb.LIBUSB_REQUEST_TYPE_CLASS | usb.LIBUSB_RECIPIENT_INTERFACE, 0, 0, 0, data.slice(1)
);
                     ^

TypeError: Cannot read property 'controlTransfer' of undefined
    at BluetoothHciSocket.write (C:\workspace\EspruinoTools\node_modules\bluetooth-hci-socket\lib\usb.js:120:22)
    at Hci.setScanEnabled (C:\workspace\EspruinoTools\node_modules\noble\lib\hci-socket\hci.js:289:16)
    at Gap.stopScanning (C:\workspace\EspruinoTools\node_modules\noble\lib\hci-socket\gap.js:33:13)
    at NobleBindings.stopScanning (C:\workspace\EspruinoTools\node_modules\noble\lib\hci-socket\bindings.js:40:13)
    at NobleBindings.onExit (C:\workspace\EspruinoTools\node_modules\noble\lib\hci-socket\bindings.js:97:8)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at processEmit [as emit] (C:\workspace\EspruinoTools\node_modules\usb\node_modules\node-pre-gyp\node_modules\npmlog\node
_modules\gauge\node_modules\signal-exit\index.js:140:35)
    at process.exit (internal/process.js:146:15)
    at C:\workspace\EspruinoTools\bin\espruino-cli.js:322:17
```

* Windows 10
* BLE-capable adaptor, **Not using the WinUSB driver**

So it's not finding any BLE devices, so first I get:

```
Error: No compatible USB Bluetooth 4.0 device found
  at BluetoothHciSocket.bindUser (C:\workspace\EspruinoTools\node_modules\bluetooth-hci-socket\lib\usb.js:70:11)
  at BluetoothHciSocket.bindRaw (C:\workspace\EspruinoTools\node_modules\bluetooth-hci-socket\lib\usb.js:28:8)
  at Hci.init (C:\workspace\EspruinoTools\node_modules\noble\lib\hci-socket\hci.js:99:35)
  at NobleBindings.init (C:\workspace\EspruinoTools\node_modules\noble\lib\hci-socket\bindings.js:83:13)
  at new Noble (C:\workspace\EspruinoTools\node_modules\noble\lib\noble.js:50:18)
  at Object.<anonymous> (C:\workspace\EspruinoTools\node_modules\noble\index.js:4:18)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
```

It could be related to https://github.com/sandeepmistry/noble/issues/382 but does appear different.

My guess is that the exception being thrown initially is leaving Noble in an odd state - where it thinks it's got an adaptor but hasn't.

My quick fix it to move the addition of the exit handlers to *after* the HCI initialisation:

```
NobleBindings.prototype.init = function() {
  this.onSigIntBinded = this.onSigInt.bind(this);

  this._gap.on('scanStart', this.onScanStart.bind(this));
  this._gap.on('scanStop', this.onScanStop.bind(this));
  this._gap.on('discover', this.onDiscover.bind(this));

  this._hci.on('stateChange', this.onStateChange.bind(this));
  this._hci.on('addressChange', this.onAddressChange.bind(this));
  this._hci.on('leConnComplete', this.onLeConnComplete.bind(this));
  this._hci.on('leConnUpdateComplete', this.onLeConnUpdateComplete.bind(this));
  this._hci.on('rssiRead', this.onRssiRead.bind(this));
  this._hci.on('disconnComplete', this.onDisconnComplete.bind(this));
  this._hci.on('encryptChange', this.onEncryptChange.bind(this));
  this._hci.on('aclDataPkt', this.onAclDataPkt.bind(this));

  this._hci.init();

  process.on('SIGINT', this.onSigIntBinded);  // <---- Moved
  process.on('exit', this.onExit.bind(this));  // <---- Moved
};
```

Not sure what you think, but that seems like a decent solution to me?

**Comment by sandeepmistry** [comment]
@gfwilliams just to confirm `this._hci.init();` is failing right?

If so, that change looks good to me, please go ahead and submit a pull request :D
