### ISSUE TITLE
Noble installation issues on Ubuntu 16.04

### ISSUE THREAD

**Issue by rand-monkey** [sandeepmistry/noble#551]
Hi Sandeep,

I am raising the noble installation issue as requested. There might be additional issues causing problems so I will post the whole story.

I am trying to get a Bluetooth Low Energy man-in-the-middle framework called Btlejuice (https://github.com/DigitalSecurity/btlejuice) to work on a Dell E7440 laptop running Ubuntu 16.04. Btlejuice is based on your noble/bleno work.

I think the problem is that the bluetooth-hci-socket is not being installed correctly on my PC.
I followed the installation instructions on your noble/bleno GitHub page.

When I run btlejuice, I get the following output ...

    **$ sudo btlejuice -u 172.16.54.128 -w
       ___ _   _       __        _         
      / __\ |_| | ___  \ \ _   _(_) ___ ___
     /__\// __| |/ _ \  \ \ | | | |/ __/ _ \
    / \/  \ |_| |  __/\_/ / |_| | | (_|  __/
    \_____/\__|_|\___\___/ \__,_|_|\___\___|

    [i] Using proxy http://172.16.54.128:8000
    [i] Using interface hci0
    2017-02-10T06:01:39.839Z - info: successfully connected to proxy
    module.js:328
        throw err;
        ^

    Error: Cannot find module 'bluetooth-hci-socket'
        at Function.Module._resolveFilename (module.js:326:15)
        at Function.Module._load (module.js:277:25)
        at Module.require (module.js:354:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (/usr/local/lib/node_modules/btlejuice/node_modules/bleno/lib/hci-socket/mgmt.js:6:26)
        at Module._compile (module.js:410:26)
        at Object.Module._extensions..js (module.js:417:10)
        at Module.load (module.js:344:32)
        at Function.Module._load (module.js:301:12)
        at Module.require (module.js:354:17)
        at require (internal/module.js:12:17)
    $**

And when I run 'sudo npm install bluetooth-hci-socket' I see:

    **$ sudo npm install bluetooth-hci-socket

    > bluetooth-hci-socket@0.5.1 install /home/user/node_modules/bluetooth-hci-socket
    > node-gyp rebuild

    make: Entering directory '/home/user/node_modules/bluetooth-hci-socket/build'
      CXX(target) Release/obj.target/binding/src/BluetoothHciSocket.o
      SOLINK_MODULE(target) Release/obj.target/binding.node
      COPY Release/binding.node
    make: Leaving directory '/home/user/node_modules/bluetooth-hci-socket/build'
    - deep-extend@0.4.1 node_modules/deep-extend
    - fstream-ignore@1.0.5 node_modules/fstream-ignore
    - ini@1.3.4 node_modules/ini
    - minimist@1.2.0 node_modules/rc/node_modules/minimist
    - strip-json-comments@1.0.4 node_modules/strip-json-comments
    - rc@1.1.6 node_modules/rc
    - ms@0.7.1 node_modules/tar-pack/node_modules/ms
    - debug@2.2.0 node_modules/tar-pack/node_modules/debug
    - once@1.3.3 node_modules/tar-pack/node_modules/once
    - readable-stream@2.1.5 node_modules/tar-pack/node_modules/readable-stream
    - uid-number@0.0.6 node_modules/uid-number
    - tar-pack@3.3.0 node_modules/tar-pack
    - node-pre-gyp@0.6.33 node_modules/node-pre-gyp
    /home/user
    ├── bleno@0.4.1
    ├── bluetooth-hci-socket@0.5.1
    ├── node-gyp@3.5.0
    └── node-waf@1.0.0

    npm WARN optional Skipping failed optional dependency /bleno/xpc-connection:
    npm WARN notsup Not compatible with your operating system or architecture: xpc-connection@0.1.4
    npm WARN enoent ENOENT: no such file or directory, open '/home/user/package.json'
    npm WARN user No description
    npm WARN user No repository field.
    npm WARN user No README data
    npm WARN user No license field.
    $**

I am not sure if those warnings are important or not?

Here's what is shown when I try re-installing bleno:

    **$ sudo npm install bleno
    /home/user
    ├── bleno@0.4.1
    ├── node-gyp@3.5.0
    └── node-waf@1.0.0

    npm WARN optional Skipping failed optional dependency /bleno/xpc-connection:
    npm WARN notsup Not compatible with your operating system or architecture: xpc-connection@0.1.4
    npm WARN enoent ENOENT: no such file or directory, open '/home/user/package.json'
    npm WARN user No description
    npm WARN user No repository field.
    npm WARN user No README data
    npm WARN user No license field.
    $**

and here's what is shown for the noble re-install:

    **$ sudo npm install noble
    /home/user
    ├── bleno@0.4.1
    ├── bluetooth-hci-socket@0.5.1
    ├── node-gyp@3.5.0
    └── node-waf@1.0.0

    npm WARN optional Skipping failed optional dependency /noble/xpc-connection:
    npm WARN notsup Not compatible with your operating system or architecture: xpc-connection@0.1.4
    npm WARN optional Skipping failed optional dependency /bleno/xpc-connection:
    npm WARN notsup Not compatible with your operating system or architecture: xpc-connection@0.1.4
    npm WARN enoent ENOENT: no such file or directory, open '/home/user/package.json'
    npm WARN user No description
    npm WARN user No repository field.
    npm WARN user No README data
    npm WARN user No license field.
    npm ERR! Linux 4.4.0-62-generic
    npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "noble"
    npm ERR! node v4.2.6
    npm ERR! npm  v3.5.2
    npm ERR! path /home/user/node_modules/noble
    npm ERR! code ENOTEMPTY
    npm ERR! errno -39
    npm ERR! syscall rename

    npm ERR! ENOTEMPTY: directory not empty, rename '/home/user/node_modules/noble' -> '/home/user/node_modules/.noble.DELETE'
    npm ERR!
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>

    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/user/npm-debug.log
    $**

Ultimately, I would like to resolve this issue with the 'bluetooth-hci-socket' not being found at runtime.

Thanks

**Comment by rand-monkey** [comment]
Got btlejuice working by deleting "node_modules" directory from home directory and reinstalling via npm.
Btlejuice no longer gets the  'bluetooth-hci-socket' error.
Sorry for any trouble.
