### ISSUE TITLE
TypeError: Cannot read property 'xxx' of undefined

### ISSUE THREAD

**Issue by JacekDob** [sandeepmistry/noble#562]
```
pi@raspberrypi ~ $ node -v
v7.4.0
```

```
/home/pi/bt/node_modules/noble/lib/hci-socket/gatt.js:618
  var characteristic = this._characteristics[serviceUuid][characteristicUuid];
                                                         ^

TypeError: Cannot read property 'd0e8434dcd290996af416c90f4e0eb2a' of undefined
    at Gatt.notify (/home/pi/bt/node_modules/noble/lib/hci-socket/gatt.js:618:58)
    at NobleBindings.notify (/home/pi/bt/node_modules/noble/lib/hci-socket/bindings.js:388:10)
    at Noble.notify (/home/pi/bt/node_modules/noble/lib/noble.js:314:19)
    at Characteristic.notify (/home/pi/bt/node_modules/noble/lib/characteristic.js:96:15)
    at EQ3BLE.NobleDevice.notifyCharacteristic (/home/pi/bt/node_modules/noble-device/lib/noble-device.js:134:18)
    at /home/pi/bt/node_modules/eq3ble/dist/index.js:90:18
    at EQ3BLE.<anonymous> (/home/pi/bt/node_modules/noble-device/lib/noble-device.js:83:7)
    at EQ3BLE.<anonymous> (/home/pi/bt/node_modules/noble-device/lib/noble-device.js:71:5)
    at Peripheral.<anonymous> (/home/pi/bt/node_modules/noble/lib/peripheral.js:101:13)
    at Service.<anonymous> (/home/pi/bt/node_modules/noble/lib/service.js:53:7)
```

**Comment by sandeepmistry** [comment]
@JacekDob please provide more details on how to reproduce this issue and re-open this issue.
