### ISSUE TITLE
Error connecting Intel Edison

### ISSUE THREAD

**Issue by ckarthik20** [sandeepmistry/noble#602]
Hi 
I'm trying to connect Intel Edison (Yocto Project) to CC2650 BLE.
Code:

> var noble = require('noble');
> var socket = require('socket.io-client')('192.168.1.7:8080');
> var IMU_SERVICE_UUID = '0xfff1';
> var AX_CHAR_UUID =  '0xfff2';
> 
> socket.on('connect', function() {
>   console.log('Connected to server');
> 
>   socket.emit('hello');
> });
> 
> noble.on('stateChange', function(state) {
>   if(state === 'poweredOn') {
>     console.log('Start BLE scan...')
>     noble.startScanning([IMU_SERVICE_UUID], false);
>   }
>   else {
>     console.log('Cannot scan... state is not poweredOn')
>     noble.stopScanning();
>   }
> });
> 
> noble.on('discover', function(peripheral) {
>   peripheral.connect(function(error) {
>     console.log('Connected to peripheral: ' + peripheral.uuid);
>     peripheral.discoverServices([IMU_SERVICE_UUID], function(error, services) {
>       var imuService = services[0];
>       console.log('Discovered IMU service');
>       imuService.discoverCharacteristics([], function(error, characteristics) {
>         characteristics.forEach(function(characteristic) {
>           emitSensorData(characteristic);
>         });
>       });
>     });
>   });
> });
> 
> function getSocketLabel(uuid) {
>   var label = null;
> 
>   if(uuid == AX_CHAR_UUID) {
>     label = 'ax:edison';
>   }
>   return label;
> }
> 
> function emitSensorData(characteristic) {
>   var socketLabel = getSocketLabel(characteristic.uuid);
>   console.log(socketLabel);
> 
>   characteristic.on('read', function(data) {
>     socket.emit(socketLabel, data.readInt32LE(0));
>   });
> 
>   characteristic.notify('true', function(error) { if (error) throw error; });
> }

Error:

> root@edison:~/edison-arduino101-iot/edison# node sensors.js
> Start BLE scan...
> Connected to peripheral: a0e6f8c4a185
> Discovered IMU service
> /home/root/edison-arduino101-iot/edison/sensors.js:37
>             services.discoverCharacteristics([], function(error, charateristics){
>                      ^
> 
> TypeError: services.discoverCharacteristics is not a function
>     at /home/root/edison-arduino101-iot/edison/sensors.js:37:15
>     at Peripheral.<anonymous> (/home/root/edison-arduino101-iot/edison/node_modules/noble/lib/peripheral.js:73:7)
>     at Peripheral.g (events.js:260:16)
>     at emitOne (events.js:77:13)
>     at Peripheral.emit (events.js:169:7)
>     at Noble.onServicesDiscover (/home/root/edison-arduino101-iot/edison/node_modules/noble/lib/noble.js:225:16)
>     at emitTwo (events.js:87:13)
>     at emit (events.js:172:7)
>     at NobleBindings.onServicesDiscovered (/home/root/edison-arduino101-iot/edison/node_modules/noble/lib/hci-socket/bindings.js:282:8)
>     at emitTwo (events.js:87:13)

How do i fix this ?

Node.js I'm in initial learning stage so any sort of assistance would be of great help!

Thanks :)

**Comment by sandeepmistry** [comment]
@ckarthik20 

`peripheral.discoverServices([IMU_SERVICE_UUID], function(error, services) {`

Are you sure the BLE peripheral contains the `IMU_SERVICE_UUID` service? Maybe you loaded the wrong sketch on the board?

If you run the `peripheral-explorer.js` example from this repo, you'll be able to determine what services are available on the peripheral.
