### ISSUE TITLE
Not able to compile my application with noble

### ISSUE THREAD

**Issue by sathish25071992** [sandeepmistry/noble#617]
Hi,

I wanted to added BLE support to my application (using electron framework). After installing noble, I am getting the following error while launching the application.

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: The module '/home/Sathish/Personal/practice/Electron FrameWork/electron-quick-start/node_modules/bluetooth-hci-socket/build/Release/b
inding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/Sathish/Personal/practice/Electron FrameWork/electron-quick-start/node_modules/bluetooth-hci-socket/lib/nat
ive.js:3:15)
    at Object.<anonymous> (/home/Sathish/Personal/practice/Electron FrameWork/electron-quick-start/node_modules/bluetooth-hci-socket/lib/nat
ive.js:17:3)
```

Am I doing something wrong?  

Thanks and regards,
Sathish V

**Comment by jacobrosenthal** [comment]
Random googling for your error "was compiled against a different Node.js version using" found this:
https://stackoverflow.com/questions/42616008/node-module-version-conflict-when-installing-modules-for-electron

And if you search the issues here, theres 12 other issues around electron that might help you as well.
https://github.com/sandeepmistry/noble/search?q=electron&type=Issues&utf8=%E2%9C%93
