### ISSUE TITLE
Noble Library not able to get RSSI updated once connected to a peripheral

### ISSUE THREAD

**Issue by GauravWable** [sandeepmistry/noble#720]
I was able to get the continuous RSSI updates where Bluetooth V4 was in place. Recently i tried to run same code on a Gateway with Bluetooth V5, and got error in following part of code

`peripheral.once('rssiUpdate', function(rssi) {
	console.log("once RSSIUpdate");
	console.log("RSSI", rssi );
});`

It throws following error

`RangeError: Index out of range
    at checkOffset (buffer.js:851:11)
    at Buffer.readUInt16LE (buffer.js:897:5)
    at Hci.processCmdCompleteEvent (/home/root/asset/Gateway-Middleware/node_modules/noble/lib/hci-socket/hci.js:594:25)
    at Hci.onSocketData (/home/root/asset/Gateway-Middleware/node_modules/noble/lib/hci-socket/hci.js:461:12)
    at emitOne (events.js:96:13)
    at BluetoothHciSocket.emit (events.js:191:7`

The peripheral object at this time is 

`Peripheral {
  _noble:
   Noble {
     state: 'poweredOn',
     address: 'ef:d0:40:6d:08:27',
     _bindings:
      NobleBindings {
        _state: 'poweredOn',
        _addresses: [Object],
        _addresseTypes: [Object],
        _connectable: [Object],
        _pendingConnectionUuid: 'b09122f6a402',
        _connectionQueue: [],
        _handles: [Object],
        _gatts: [Object],
        _aclStreams: [Object],
        _signalings: [Object],
        _hci: [Object],
        _gap: [Object],
        _events: [Object],
        _eventsCount: 21,
        onSigIntBinded: [Function: bound ],
        _scanServiceUuids: [] },
     _peripherals:
      { '0e0800f14a9f': [Object],
        '1ce1e548043b': [Object],
        e40439752344: [Object],
        '113928598c47': [Object],
        e3ef59c45791: [Object],
        '00ea2302c684': [Object],
        d21453709a19: [Object],
        fd9e364f81d3: [Object],
        f99a324b7dcf: [Object],
        e20100028140: [Object],
        d41655729c1b: [Object],
        d61857749e1d: [Object],
        '00ea2302c687': [Object],
        '059a42a15cb4': [Object],
        fb9c344d7fd1: [Object],
        '5b6e31fb3429': [Object],
        b09122f6a402: [Circular],
        '58acfd1fd262': [Object] },
     _services:
      { '0e0800f14a9f': {},
        '1ce1e548043b': {},
        e40439752344: {},
        '113928598c47': {},
        e3ef59c45791: {},
        '00ea2302c684': {},
        d21453709a19: {},
        fd9e364f81d3: {},
        f99a324b7dcf: {},
        e20100028140: {},
        d41655729c1b: {},
        d61857749e1d: {},
        '00ea2302c687': {},
        '059a42a15cb4': {},
        fb9c344d7fd1: {},
        '5b6e31fb3429': {},
        b09122f6a402: {},
        '58acfd1fd262': {} },
     _characteristics:
      { '0e0800f14a9f': {},
        '1ce1e548043b': {},
        e40439752344: {},
        '113928598c47': {},
        e3ef59c45791: {},
        '00ea2302c684': {},
        d21453709a19: {},
        fd9e364f81d3: {},
        f99a324b7dcf: {},
        e20100028140: {},
        d41655729c1b: {},
        d61857749e1d: {},
        '00ea2302c687': {},
        '059a42a15cb4': {},
        fb9c344d7fd1: {},
        '5b6e31fb3429': {},
        b09122f6a402: {},
        '58acfd1fd262': {} },
     _descriptors:
      { '0e0800f14a9f': {},
        '1ce1e548043b': {},
        e40439752344: {},
        '113928598c47': {},
        e3ef59c45791: {},
        '00ea2302c684': {},
        d21453709a19: {},
        fd9e364f81d3: {},
        f99a324b7dcf: {},
        e20100028140: {},
        d41655729c1b: {},
        d61857749e1d: {},
        '00ea2302c687': {},
        '059a42a15cb4': {},
        fb9c344d7fd1: {},
        '5b6e31fb3429': {},
        b09122f6a402: {},
        '58acfd1fd262': {} },
     _discoveredPeripheralUUids:
      [ '0e0800f14a9f',
        '1ce1e548043b',
        'e40439752344',
        '113928598c47',
        'e3ef59c45791',
        '00ea2302c684',
        'd21453709a19',
        'fd9e364f81d3',
        'f99a324b7dcf',
        'e20100028140',
        'd41655729c1b',
        'd61857749e1d',
        '00ea2302c687',
        '059a42a15cb4',
        'fb9c344d7fd1',
        '5b6e31fb3429',
        'b09122f6a402',
        '58acfd1fd262' ],
     _events:
      { warning: [Function: bound ],
        stateChange: [Object],
        discover: [Function],
        scanStop: [Function] },
     _eventsCount: 4,
     _allowDuplicates: false },
  id: 'b09122f6a402',
  uuid: 'b09122f6a402',
  address: 'b0:91:22:f6:a4:02',
  addressType: 'public',
  connectable: true,
  advertisement:
   { localName: 'CC2650 SensorTag',
     txPowerLevel: 0,
     manufacturerData: <Buffer 0d 00 03 00 00>,
     serviceData: [],
     serviceUuids: [ 'aa80' ],
     solicitationServiceUuids: [],
     serviceSolicitationUuids: [] },
  rssi: -55,
  services: null,
  state: 'connected',
  _events:
   { disconnect: { [Function: bound onceWrapper] listener: [Function] },
     rssiUpdate: { [Function: bound onceWrapper] listener: [Function] } },
  _eventsCount: 2 }`

Here i can see `rssi: -55` means RSSI value is there.

Can you please help me to solve this issue.

**Comment by rzr** [comment]
It looks the maintenance of this project is in pause, but feel free to contribute to @abandonware fork until upstream is active again

Feel free to comment:
https://github.com/abandonware/noble/issues/2
