### ISSUE TITLE
characteristicsUuids.indexOf is not a function

### ISSUE THREAD

**Issue by LeslieAerts** [sandeepmistry/noble#731]
When executing this basic discovery test, I encounter the following error:

```javascript
noble.on('discover', function (peripheral) {
  // Connect to the first Thingy you can find
  console.log("Starting discovery...");
  noble.stopScanning();

  peripheral.connect(function (error) {
    console.log("Peripheral found...");
    if (error != null) {
      baseError('connecting', error);
      return;
    }

    peripheral.discoverServices(discoverServices);
  });
});

function discoverServices(error, services) {
  if (error) {
    baseError('discover services', error);
    return;
  }

  services.forEach(function (element) {
    element.discoverCharacteristics(discoverCharacteristics);
  }, this);
};

function discoverCharacteristics(error, characteristics) {
  if (error) {
    baseError('discover characteristics', error);
    return;
  }
}
```

```
TypeError: characteristicUuids.indexOf is not a function
    at Gatt.<anonymous> (<project>/node_modules/noble/lib/hci-socket/gatt.js:487:69)
    at Gatt.onAclStreamData (<project>/node_modules/noble/lib/hci-socket/gatt.js:132:26)
    at emitTwo (events.js:131:20)
    at AclStream.emit (events.js:214:7)
    at AclStream.push (<project>/node_modules/noble/lib/hci-socket/acl-stream.js:35:10)
    at NobleBindings.onAclDataPkt (<project>/node_modules/noble/lib/hci-socket/bindings.js:286:15)
    at emitThree (events.js:136:13)
    at Hci.emit (events.js:217:7)
    at Hci.onSocketData (<project>/node_modules/noble/lib/hci-socket/hci.js:516:14)
    at emitOne (events.js:116:13)

```

Seems to be more of an hci-socket issue than noble, but I'm dropping it here as well...

**Comment by sandeepmistry** [comment]
Please see https://github.com/sandeepmistry/noble#discover-characteristics.
